name: validate
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  validate-configs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: brokeyourbike/ocvalidate-action@v0.3
        with:
          opencore-version: '0.8.8' # OpenCore version to download and use.
      - run: ocvalidate EFI/OC/config.plist | grep -q 'No issues found'
